#!/usr/bin/env bash

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install zsh
brew install zsh
chsh -s /usr/local/bin/zsh

# install omz
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install non powerline agnoster theme
git clone git@github.com:fletom/agnoster-no-powerline-zsh-theme.git ~/agnoster-no-powerline
cp ~/agnoster-no-powerline/agnoster-no-powerline.zsh-theme ~/.oh-my-zsh/themes
rm -rf ~/agnoster-no-powerline
echo ZSH_THEME="agnoster-no-powerline"\n >> ~/.zshrc

# install The Fuck
brew install thefuck
echo 'eval $(thefuck --alias)\n' >> ~/.zshrc

# install rectangle
brew install rectangle

# install VSCode
brew install --cask visual-studio-code

# install WhatsApp
brew install --cask whatsapp

# install Todoist
brew install --cask todoist

# install Spotify
brew install --cask spotify

# install Discord
brew install --cask discord

# install Steam
brew install --cask steam

# install OBS
brew install --cask obs

# install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

# add nvm to .zshrc
echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >> ~/.zshrc
echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >> ~/.zshrc

# install node lts
nvm install --lts

# install pnpm
npm install -g pnpm